version: "3.8"

services:
  mysql-ngobrol:
    image: mysql:latest
    container_name: mysql-ngobrol
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql-ngobrol
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  postgres-ngobrol:
    image: postgres:15.3-alpine3.18
    container_name: postgres-ngobrol
    restart: always
    ports:
      - "10543:5432"
    environment:
      POSTGRES_PASSWORD: postgres-ngobrol
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M